### ISSUE TITLE
Launch files not included in indigo deb?

### ISSUE THREAD

**Issue by bhaskara** [PickNikRobotics/tf_keyboard_cal#10]
After apt-get installing ros-indigo-tf-keyboard-cal, I'm not able to roslaunch the files mentioned in the readme.

**Comment by davetcoleman** [comment]
This was fixed but never released: https://github.com/davetcoleman/tf_keyboard_cal/commit/a4f4cf385dfd97e770ad78e3d6418ebe4d4f8b37

**Comment by davetcoleman** [comment]
You'll need to build from source until the next indigo sync

https://github.com/ros/rosdistro/pull/12042
