### ISSUE TITLE
Install launch files

### ISSUE THREAD

**Issue by galou** [PickNikRobotics/tf_keyboard_cal#4]
I appears that launch files are not packaged.

I think adding this line to `CMakeLists.txt` would solve the problem:

```
install(DIRECTORY launch DESTINATION ${CATKIN_PACKAGE_SHARE_DESTINATION})
```

**Comment by davetcoleman** [comment]
Indeed I seem to have missed that. Could you create a quick PR for it?

**Comment by galou** [comment]
Cf. #5.
