### ISSUE TITLE
Missing info in Readme

### ISSUE THREAD

**Issue by Squelsh** [PickNikRobotics/tf_keyboard_cal#7]
Hi!

First: Thanks for that extremely useful package! I always used a URDF robot with 6 joints and a robot state publisher to create a movable tf that I could control with the joint_state_publisher GUI (:

But: I missed the info on where to get ros_keyboard. Perhaps you could put a link in your readme to that package.

Cheers,
Andreas

**Comment by davetcoleman** [comment]
I just updated the README, see https://github.com/davetcoleman/tf_keyboard_cal#build-from-source

In particular "be sure to install necessary dependencies by running the following command in the root of your catkin workspace:"
